<?php
/**
 * CheckStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Onfido Public API v3.6
 *
 * The Onfido Public API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Onfido\Model;
use \Onfido\ObjectSerializer;

/**
 * CheckStatus Class Doc Comment
 *
 * @category Class
 * @description The current state of the check in the checking process.
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CheckStatus
{
    /**
     * Possible values of this enum
     */
    public const IN_PROGRESS = 'in_progress';

    public const AWAITING_APPLICANT = 'awaiting_applicant';

    public const COMPLETE = 'complete';

    public const WITHDRAWN = 'withdrawn';

    public const PAUSED = 'paused';

    public const REOPENED = 'reopened';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::IN_PROGRESS,
            self::AWAITING_APPLICANT,
            self::COMPLETE,
            self::WITHDRAWN,
            self::PAUSED,
            self::REOPENED,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}


