<?php
/**
 * DocumentBreakdownImageIntegrityBreakdown
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Onfido API v3.6
 *
 * The Onfido API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Onfido\Model;

use \ArrayAccess;
use \Onfido\ObjectSerializer;

/**
 * DocumentBreakdownImageIntegrityBreakdown Class Doc Comment
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DocumentBreakdownImageIntegrityBreakdown implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'document_breakdown_image_integrity_breakdown';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'image_quality' => '\Onfido\Model\DocumentBreakdownImageIntegrityBreakdownImageQuality',
        'supported_document' => '\Onfido\Model\DocumentBreakdownImageIntegrityBreakdownSupportedDocument',
        'colour_picture' => '\Onfido\Model\DocumentBreakdownImageIntegrityBreakdownColourPicture',
        'conclusive_document_quality' => '\Onfido\Model\DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'image_quality' => null,
        'supported_document' => null,
        'colour_picture' => null,
        'conclusive_document_quality' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'image_quality' => false,
        'supported_document' => false,
        'colour_picture' => false,
        'conclusive_document_quality' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'image_quality' => 'image_quality',
        'supported_document' => 'supported_document',
        'colour_picture' => 'colour_picture',
        'conclusive_document_quality' => 'conclusive_document_quality'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'image_quality' => 'setImageQuality',
        'supported_document' => 'setSupportedDocument',
        'colour_picture' => 'setColourPicture',
        'conclusive_document_quality' => 'setConclusiveDocumentQuality'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'image_quality' => 'getImageQuality',
        'supported_document' => 'getSupportedDocument',
        'colour_picture' => 'getColourPicture',
        'conclusive_document_quality' => 'getConclusiveDocumentQuality'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('image_quality', $data ?? [], null);
        $this->setIfExists('supported_document', $data ?? [], null);
        $this->setIfExists('colour_picture', $data ?? [], null);
        $this->setIfExists('conclusive_document_quality', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets image_quality
     *
     * @return \Onfido\Model\DocumentBreakdownImageIntegrityBreakdownImageQuality|null
     */
    public function getImageQuality()
    {
        return $this->container['image_quality'];
    }

    /**
     * Sets image_quality
     *
     * @param \Onfido\Model\DocumentBreakdownImageIntegrityBreakdownImageQuality|null $image_quality image_quality
     *
     * @return self
     */
    public function setImageQuality($image_quality)
    {
        if (is_null($image_quality)) {
            throw new \InvalidArgumentException('non-nullable image_quality cannot be null');
        }
        $this->container['image_quality'] = $image_quality;

        return $this;
    }

    /**
     * Gets supported_document
     *
     * @return \Onfido\Model\DocumentBreakdownImageIntegrityBreakdownSupportedDocument|null
     */
    public function getSupportedDocument()
    {
        return $this->container['supported_document'];
    }

    /**
     * Sets supported_document
     *
     * @param \Onfido\Model\DocumentBreakdownImageIntegrityBreakdownSupportedDocument|null $supported_document supported_document
     *
     * @return self
     */
    public function setSupportedDocument($supported_document)
    {
        if (is_null($supported_document)) {
            throw new \InvalidArgumentException('non-nullable supported_document cannot be null');
        }
        $this->container['supported_document'] = $supported_document;

        return $this;
    }

    /**
     * Gets colour_picture
     *
     * @return \Onfido\Model\DocumentBreakdownImageIntegrityBreakdownColourPicture|null
     */
    public function getColourPicture()
    {
        return $this->container['colour_picture'];
    }

    /**
     * Sets colour_picture
     *
     * @param \Onfido\Model\DocumentBreakdownImageIntegrityBreakdownColourPicture|null $colour_picture colour_picture
     *
     * @return self
     */
    public function setColourPicture($colour_picture)
    {
        if (is_null($colour_picture)) {
            throw new \InvalidArgumentException('non-nullable colour_picture cannot be null');
        }
        $this->container['colour_picture'] = $colour_picture;

        return $this;
    }

    /**
     * Gets conclusive_document_quality
     *
     * @return \Onfido\Model\DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality|null
     */
    public function getConclusiveDocumentQuality()
    {
        return $this->container['conclusive_document_quality'];
    }

    /**
     * Sets conclusive_document_quality
     *
     * @param \Onfido\Model\DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality|null $conclusive_document_quality conclusive_document_quality
     *
     * @return self
     */
    public function setConclusiveDocumentQuality($conclusive_document_quality)
    {
        if (is_null($conclusive_document_quality)) {
            throw new \InvalidArgumentException('non-nullable conclusive_document_quality cannot be null');
        }
        $this->container['conclusive_document_quality'] = $conclusive_document_quality;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

}


