<?php
/**
 * ExtractionExtractedData
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Onfido API v3.6
 *
 * The Onfido API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Onfido\Model;

use \ArrayAccess;
use \Onfido\ObjectSerializer;

/**
 * ExtractionExtractedData Class Doc Comment
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ExtractionExtractedData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'extraction_extracted_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'document_number' => 'string',
        'first_name' => 'string',
        'last_name' => 'string',
        'full_name' => 'string',
        'spouse_name' => 'string',
        'widow_name' => 'string',
        'alias_name' => 'string',
        'gender' => 'string',
        'date_of_birth' => '\DateTime',
        'date_of_expiry' => '\DateTime',
        'expiry_date' => '\DateTime',
        'nationality' => 'string',
        'mrz_line_1' => 'string',
        'mrz_line_2' => 'string',
        'mrz_line_3' => 'string',
        'address_1' => 'string',
        'address_2' => 'string',
        'address_3' => 'string',
        'address_4' => 'string',
        'address_5' => 'string',
        'issuing_authority' => 'string',
        'issuing_country' => '\Onfido\Model\CountryCodes',
        'document_type' => '\Onfido\Model\DocumentTypes',
        'place_of_birth' => 'string',
        'issuing_state' => 'string',
        'issuing_date' => '\DateTime',
        'personal_number' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'document_number' => null,
        'first_name' => null,
        'last_name' => null,
        'full_name' => null,
        'spouse_name' => null,
        'widow_name' => null,
        'alias_name' => null,
        'gender' => null,
        'date_of_birth' => 'date',
        'date_of_expiry' => 'date',
        'expiry_date' => 'date',
        'nationality' => null,
        'mrz_line_1' => null,
        'mrz_line_2' => null,
        'mrz_line_3' => null,
        'address_1' => null,
        'address_2' => null,
        'address_3' => null,
        'address_4' => null,
        'address_5' => null,
        'issuing_authority' => null,
        'issuing_country' => null,
        'document_type' => null,
        'place_of_birth' => null,
        'issuing_state' => null,
        'issuing_date' => 'date',
        'personal_number' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'document_number' => false,
        'first_name' => false,
        'last_name' => false,
        'full_name' => false,
        'spouse_name' => false,
        'widow_name' => false,
        'alias_name' => false,
        'gender' => false,
        'date_of_birth' => false,
        'date_of_expiry' => false,
        'expiry_date' => false,
        'nationality' => false,
        'mrz_line_1' => false,
        'mrz_line_2' => false,
        'mrz_line_3' => false,
        'address_1' => false,
        'address_2' => false,
        'address_3' => false,
        'address_4' => false,
        'address_5' => false,
        'issuing_authority' => false,
        'issuing_country' => false,
        'document_type' => false,
        'place_of_birth' => false,
        'issuing_state' => false,
        'issuing_date' => false,
        'personal_number' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'document_number' => 'document_number',
        'first_name' => 'first_name',
        'last_name' => 'last_name',
        'full_name' => 'full_name',
        'spouse_name' => 'spouse_name',
        'widow_name' => 'widow_name',
        'alias_name' => 'alias_name',
        'gender' => 'gender',
        'date_of_birth' => 'date_of_birth',
        'date_of_expiry' => 'date_of_expiry',
        'expiry_date' => 'expiry_date',
        'nationality' => 'nationality',
        'mrz_line_1' => 'mrz_line_1',
        'mrz_line_2' => 'mrz_line_2',
        'mrz_line_3' => 'mrz_line_3',
        'address_1' => 'address_1',
        'address_2' => 'address_2',
        'address_3' => 'address_3',
        'address_4' => 'address_4',
        'address_5' => 'address_5',
        'issuing_authority' => 'issuing_authority',
        'issuing_country' => 'issuing_country',
        'document_type' => 'document_type',
        'place_of_birth' => 'place_of_birth',
        'issuing_state' => 'issuing_state',
        'issuing_date' => 'issuing_date',
        'personal_number' => 'personal_number'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'document_number' => 'setDocumentNumber',
        'first_name' => 'setFirstName',
        'last_name' => 'setLastName',
        'full_name' => 'setFullName',
        'spouse_name' => 'setSpouseName',
        'widow_name' => 'setWidowName',
        'alias_name' => 'setAliasName',
        'gender' => 'setGender',
        'date_of_birth' => 'setDateOfBirth',
        'date_of_expiry' => 'setDateOfExpiry',
        'expiry_date' => 'setExpiryDate',
        'nationality' => 'setNationality',
        'mrz_line_1' => 'setMrzLine1',
        'mrz_line_2' => 'setMrzLine2',
        'mrz_line_3' => 'setMrzLine3',
        'address_1' => 'setAddress1',
        'address_2' => 'setAddress2',
        'address_3' => 'setAddress3',
        'address_4' => 'setAddress4',
        'address_5' => 'setAddress5',
        'issuing_authority' => 'setIssuingAuthority',
        'issuing_country' => 'setIssuingCountry',
        'document_type' => 'setDocumentType',
        'place_of_birth' => 'setPlaceOfBirth',
        'issuing_state' => 'setIssuingState',
        'issuing_date' => 'setIssuingDate',
        'personal_number' => 'setPersonalNumber'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'document_number' => 'getDocumentNumber',
        'first_name' => 'getFirstName',
        'last_name' => 'getLastName',
        'full_name' => 'getFullName',
        'spouse_name' => 'getSpouseName',
        'widow_name' => 'getWidowName',
        'alias_name' => 'getAliasName',
        'gender' => 'getGender',
        'date_of_birth' => 'getDateOfBirth',
        'date_of_expiry' => 'getDateOfExpiry',
        'expiry_date' => 'getExpiryDate',
        'nationality' => 'getNationality',
        'mrz_line_1' => 'getMrzLine1',
        'mrz_line_2' => 'getMrzLine2',
        'mrz_line_3' => 'getMrzLine3',
        'address_1' => 'getAddress1',
        'address_2' => 'getAddress2',
        'address_3' => 'getAddress3',
        'address_4' => 'getAddress4',
        'address_5' => 'getAddress5',
        'issuing_authority' => 'getIssuingAuthority',
        'issuing_country' => 'getIssuingCountry',
        'document_type' => 'getDocumentType',
        'place_of_birth' => 'getPlaceOfBirth',
        'issuing_state' => 'getIssuingState',
        'issuing_date' => 'getIssuingDate',
        'personal_number' => 'getPersonalNumber'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const GENDER_MALE = 'Male';
    public const GENDER_FEMALE = 'Female';
    public const GENDER_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getGenderAllowableValues()
    {
        return [
            self::GENDER_MALE,
            self::GENDER_FEMALE,
            self::GENDER_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('document_number', $data ?? [], null);
        $this->setIfExists('first_name', $data ?? [], null);
        $this->setIfExists('last_name', $data ?? [], null);
        $this->setIfExists('full_name', $data ?? [], null);
        $this->setIfExists('spouse_name', $data ?? [], null);
        $this->setIfExists('widow_name', $data ?? [], null);
        $this->setIfExists('alias_name', $data ?? [], null);
        $this->setIfExists('gender', $data ?? [], null);
        $this->setIfExists('date_of_birth', $data ?? [], null);
        $this->setIfExists('date_of_expiry', $data ?? [], null);
        $this->setIfExists('expiry_date', $data ?? [], null);
        $this->setIfExists('nationality', $data ?? [], null);
        $this->setIfExists('mrz_line_1', $data ?? [], null);
        $this->setIfExists('mrz_line_2', $data ?? [], null);
        $this->setIfExists('mrz_line_3', $data ?? [], null);
        $this->setIfExists('address_1', $data ?? [], null);
        $this->setIfExists('address_2', $data ?? [], null);
        $this->setIfExists('address_3', $data ?? [], null);
        $this->setIfExists('address_4', $data ?? [], null);
        $this->setIfExists('address_5', $data ?? [], null);
        $this->setIfExists('issuing_authority', $data ?? [], null);
        $this->setIfExists('issuing_country', $data ?? [], null);
        $this->setIfExists('document_type', $data ?? [], null);
        $this->setIfExists('place_of_birth', $data ?? [], null);
        $this->setIfExists('issuing_state', $data ?? [], null);
        $this->setIfExists('issuing_date', $data ?? [], null);
        $this->setIfExists('personal_number', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getGenderAllowableValues();
        if (!is_null($this->container['gender']) && !in_array($this->container['gender'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'gender', must be one of '%s'",
                $this->container['gender'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['nationality']) && !preg_match("/^[A-Z]{3}$/", $this->container['nationality'])) {
            $invalidProperties[] = "invalid value for 'nationality', must be conform to the pattern /^[A-Z]{3}$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets document_number
     *
     * @return string|null
     */
    public function getDocumentNumber()
    {
        return $this->container['document_number'];
    }

    /**
     * Sets document_number
     *
     * @param string|null $document_number The official document number.
     *
     * @return self
     */
    public function setDocumentNumber($document_number)
    {
        if (is_null($document_number)) {
            throw new \InvalidArgumentException('non-nullable document_number cannot be null');
        }
        $this->container['document_number'] = $document_number;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string|null
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string|null $first_name First name.
     *
     * @return self
     */
    public function setFirstName($first_name)
    {
        if (is_null($first_name)) {
            throw new \InvalidArgumentException('non-nullable first_name cannot be null');
        }
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string|null
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string|null $last_name Last name.
     *
     * @return self
     */
    public function setLastName($last_name)
    {
        if (is_null($last_name)) {
            throw new \InvalidArgumentException('non-nullable last_name cannot be null');
        }
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets full_name
     *
     * @return string|null
     */
    public function getFullName()
    {
        return $this->container['full_name'];
    }

    /**
     * Sets full_name
     *
     * @param string|null $full_name Full name.
     *
     * @return self
     */
    public function setFullName($full_name)
    {
        if (is_null($full_name)) {
            throw new \InvalidArgumentException('non-nullable full_name cannot be null');
        }
        $this->container['full_name'] = $full_name;

        return $this;
    }

    /**
     * Gets spouse_name
     *
     * @return string|null
     */
    public function getSpouseName()
    {
        return $this->container['spouse_name'];
    }

    /**
     * Sets spouse_name
     *
     * @param string|null $spouse_name Spouse name (French documents only).
     *
     * @return self
     */
    public function setSpouseName($spouse_name)
    {
        if (is_null($spouse_name)) {
            throw new \InvalidArgumentException('non-nullable spouse_name cannot be null');
        }
        $this->container['spouse_name'] = $spouse_name;

        return $this;
    }

    /**
     * Gets widow_name
     *
     * @return string|null
     */
    public function getWidowName()
    {
        return $this->container['widow_name'];
    }

    /**
     * Sets widow_name
     *
     * @param string|null $widow_name Widow name (French documents only).
     *
     * @return self
     */
    public function setWidowName($widow_name)
    {
        if (is_null($widow_name)) {
            throw new \InvalidArgumentException('non-nullable widow_name cannot be null');
        }
        $this->container['widow_name'] = $widow_name;

        return $this;
    }

    /**
     * Gets alias_name
     *
     * @return string|null
     */
    public function getAliasName()
    {
        return $this->container['alias_name'];
    }

    /**
     * Sets alias_name
     *
     * @param string|null $alias_name Alias name (French documents only).
     *
     * @return self
     */
    public function setAliasName($alias_name)
    {
        if (is_null($alias_name)) {
            throw new \InvalidArgumentException('non-nullable alias_name cannot be null');
        }
        $this->container['alias_name'] = $alias_name;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return string|null
     */
    public function getGender()
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param string|null $gender Gender (Valid values are Male and Female).
     *
     * @return self
     */
    public function setGender($gender)
    {
        if (is_null($gender)) {
            throw new \InvalidArgumentException('non-nullable gender cannot be null');
        }
        $allowedValues = $this->getGenderAllowableValues();
        if (!in_array($gender, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'gender', must be one of '%s'",
                    $gender,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets date_of_birth
     *
     * @return \DateTime|null
     */
    public function getDateOfBirth()
    {
        return $this->container['date_of_birth'];
    }

    /**
     * Sets date_of_birth
     *
     * @param \DateTime|null $date_of_birth Date of birth in YYYY-MM-DD format.
     *
     * @return self
     */
    public function setDateOfBirth($date_of_birth)
    {
        if (is_null($date_of_birth)) {
            throw new \InvalidArgumentException('non-nullable date_of_birth cannot be null');
        }
        $this->container['date_of_birth'] = $date_of_birth;

        return $this;
    }

    /**
     * Gets date_of_expiry
     *
     * @return \DateTime|null
     */
    public function getDateOfExpiry()
    {
        return $this->container['date_of_expiry'];
    }

    /**
     * Sets date_of_expiry
     *
     * @param \DateTime|null $date_of_expiry Date of expiry in YYYY-MM-DD format.
     *
     * @return self
     */
    public function setDateOfExpiry($date_of_expiry)
    {
        if (is_null($date_of_expiry)) {
            throw new \InvalidArgumentException('non-nullable date_of_expiry cannot be null');
        }
        $this->container['date_of_expiry'] = $date_of_expiry;

        return $this;
    }

    /**
     * Gets expiry_date
     *
     * @return \DateTime|null
     */
    public function getExpiryDate()
    {
        return $this->container['expiry_date'];
    }

    /**
     * Sets expiry_date
     *
     * @param \DateTime|null $expiry_date Date of expiry in YYYY-MM-DD format.
     *
     * @return self
     */
    public function setExpiryDate($expiry_date)
    {
        if (is_null($expiry_date)) {
            throw new \InvalidArgumentException('non-nullable expiry_date cannot be null');
        }
        $this->container['expiry_date'] = $expiry_date;

        return $this;
    }

    /**
     * Gets nationality
     *
     * @return string|null
     */
    public function getNationality()
    {
        return $this->container['nationality'];
    }

    /**
     * Sets nationality
     *
     * @param string|null $nationality Nationality in 3-letter ISO code.
     *
     * @return self
     */
    public function setNationality($nationality)
    {
        if (is_null($nationality)) {
            throw new \InvalidArgumentException('non-nullable nationality cannot be null');
        }

        if ((!preg_match("/^[A-Z]{3}$/", ObjectSerializer::toString($nationality)))) {
            throw new \InvalidArgumentException("invalid value for \$nationality when calling ExtractionExtractedData., must conform to the pattern /^[A-Z]{3}$/.");
        }

        $this->container['nationality'] = $nationality;

        return $this;
    }

    /**
     * Gets mrz_line_1
     *
     * @return string|null
     */
    public function getMrzLine1()
    {
        return $this->container['mrz_line_1'];
    }

    /**
     * Sets mrz_line_1
     *
     * @param string|null $mrz_line_1 Line 1 of the MRZ code.
     *
     * @return self
     */
    public function setMrzLine1($mrz_line_1)
    {
        if (is_null($mrz_line_1)) {
            throw new \InvalidArgumentException('non-nullable mrz_line_1 cannot be null');
        }
        $this->container['mrz_line_1'] = $mrz_line_1;

        return $this;
    }

    /**
     * Gets mrz_line_2
     *
     * @return string|null
     */
    public function getMrzLine2()
    {
        return $this->container['mrz_line_2'];
    }

    /**
     * Sets mrz_line_2
     *
     * @param string|null $mrz_line_2 Line 2 of the MRZ code.
     *
     * @return self
     */
    public function setMrzLine2($mrz_line_2)
    {
        if (is_null($mrz_line_2)) {
            throw new \InvalidArgumentException('non-nullable mrz_line_2 cannot be null');
        }
        $this->container['mrz_line_2'] = $mrz_line_2;

        return $this;
    }

    /**
     * Gets mrz_line_3
     *
     * @return string|null
     */
    public function getMrzLine3()
    {
        return $this->container['mrz_line_3'];
    }

    /**
     * Sets mrz_line_3
     *
     * @param string|null $mrz_line_3 Line 3 of the MRZ code.
     *
     * @return self
     */
    public function setMrzLine3($mrz_line_3)
    {
        if (is_null($mrz_line_3)) {
            throw new \InvalidArgumentException('non-nullable mrz_line_3 cannot be null');
        }
        $this->container['mrz_line_3'] = $mrz_line_3;

        return $this;
    }

    /**
     * Gets address_1
     *
     * @return string|null
     */
    public function getAddress1()
    {
        return $this->container['address_1'];
    }

    /**
     * Sets address_1
     *
     * @param string|null $address_1 Line 1 of the address.
     *
     * @return self
     */
    public function setAddress1($address_1)
    {
        if (is_null($address_1)) {
            throw new \InvalidArgumentException('non-nullable address_1 cannot be null');
        }
        $this->container['address_1'] = $address_1;

        return $this;
    }

    /**
     * Gets address_2
     *
     * @return string|null
     */
    public function getAddress2()
    {
        return $this->container['address_2'];
    }

    /**
     * Sets address_2
     *
     * @param string|null $address_2 Line 2 of the address.
     *
     * @return self
     */
    public function setAddress2($address_2)
    {
        if (is_null($address_2)) {
            throw new \InvalidArgumentException('non-nullable address_2 cannot be null');
        }
        $this->container['address_2'] = $address_2;

        return $this;
    }

    /**
     * Gets address_3
     *
     * @return string|null
     */
    public function getAddress3()
    {
        return $this->container['address_3'];
    }

    /**
     * Sets address_3
     *
     * @param string|null $address_3 Line 3 of the address.
     *
     * @return self
     */
    public function setAddress3($address_3)
    {
        if (is_null($address_3)) {
            throw new \InvalidArgumentException('non-nullable address_3 cannot be null');
        }
        $this->container['address_3'] = $address_3;

        return $this;
    }

    /**
     * Gets address_4
     *
     * @return string|null
     */
    public function getAddress4()
    {
        return $this->container['address_4'];
    }

    /**
     * Sets address_4
     *
     * @param string|null $address_4 Line 4 of the address.
     *
     * @return self
     */
    public function setAddress4($address_4)
    {
        if (is_null($address_4)) {
            throw new \InvalidArgumentException('non-nullable address_4 cannot be null');
        }
        $this->container['address_4'] = $address_4;

        return $this;
    }

    /**
     * Gets address_5
     *
     * @return string|null
     */
    public function getAddress5()
    {
        return $this->container['address_5'];
    }

    /**
     * Sets address_5
     *
     * @param string|null $address_5 Line 5 of the address.
     *
     * @return self
     */
    public function setAddress5($address_5)
    {
        if (is_null($address_5)) {
            throw new \InvalidArgumentException('non-nullable address_5 cannot be null');
        }
        $this->container['address_5'] = $address_5;

        return $this;
    }

    /**
     * Gets issuing_authority
     *
     * @return string|null
     */
    public function getIssuingAuthority()
    {
        return $this->container['issuing_authority'];
    }

    /**
     * Sets issuing_authority
     *
     * @param string|null $issuing_authority Issuing authority.
     *
     * @return self
     */
    public function setIssuingAuthority($issuing_authority)
    {
        if (is_null($issuing_authority)) {
            throw new \InvalidArgumentException('non-nullable issuing_authority cannot be null');
        }
        $this->container['issuing_authority'] = $issuing_authority;

        return $this;
    }

    /**
     * Gets issuing_country
     *
     * @return \Onfido\Model\CountryCodes|null
     */
    public function getIssuingCountry()
    {
        return $this->container['issuing_country'];
    }

    /**
     * Sets issuing_country
     *
     * @param \Onfido\Model\CountryCodes|null $issuing_country Document country in 3-letter ISO code.
     *
     * @return self
     */
    public function setIssuingCountry($issuing_country)
    {
        if (is_null($issuing_country)) {
            throw new \InvalidArgumentException('non-nullable issuing_country cannot be null');
        }
        $this->container['issuing_country'] = $issuing_country;

        return $this;
    }

    /**
     * Gets document_type
     *
     * @return \Onfido\Model\DocumentTypes|null
     */
    public function getDocumentType()
    {
        return $this->container['document_type'];
    }

    /**
     * Sets document_type
     *
     * @param \Onfido\Model\DocumentTypes|null $document_type Type of document.
     *
     * @return self
     */
    public function setDocumentType($document_type)
    {
        if (is_null($document_type)) {
            throw new \InvalidArgumentException('non-nullable document_type cannot be null');
        }
        $this->container['document_type'] = $document_type;

        return $this;
    }

    /**
     * Gets place_of_birth
     *
     * @return string|null
     */
    public function getPlaceOfBirth()
    {
        return $this->container['place_of_birth'];
    }

    /**
     * Sets place_of_birth
     *
     * @param string|null $place_of_birth Place of birth.
     *
     * @return self
     */
    public function setPlaceOfBirth($place_of_birth)
    {
        if (is_null($place_of_birth)) {
            throw new \InvalidArgumentException('non-nullable place_of_birth cannot be null');
        }
        $this->container['place_of_birth'] = $place_of_birth;

        return $this;
    }

    /**
     * Gets issuing_state
     *
     * @return string|null
     */
    public function getIssuingState()
    {
        return $this->container['issuing_state'];
    }

    /**
     * Sets issuing_state
     *
     * @param string|null $issuing_state The state that issued the document.
     *
     * @return self
     */
    public function setIssuingState($issuing_state)
    {
        if (is_null($issuing_state)) {
            throw new \InvalidArgumentException('non-nullable issuing_state cannot be null');
        }
        $this->container['issuing_state'] = $issuing_state;

        return $this;
    }

    /**
     * Gets issuing_date
     *
     * @return \DateTime|null
     */
    public function getIssuingDate()
    {
        return $this->container['issuing_date'];
    }

    /**
     * Sets issuing_date
     *
     * @param \DateTime|null $issuing_date Issuing date in YYYY-MM-DD format.
     *
     * @return self
     */
    public function setIssuingDate($issuing_date)
    {
        if (is_null($issuing_date)) {
            throw new \InvalidArgumentException('non-nullable issuing_date cannot be null');
        }
        $this->container['issuing_date'] = $issuing_date;

        return $this;
    }

    /**
     * Gets personal_number
     *
     * @return string|null
     */
    public function getPersonalNumber()
    {
        return $this->container['personal_number'];
    }

    /**
     * Sets personal_number
     *
     * @param string|null $personal_number The owner's unique identification number.
     *
     * @return self
     */
    public function setPersonalNumber($personal_number)
    {
        if (is_null($personal_number)) {
            throw new \InvalidArgumentException('non-nullable personal_number cannot be null');
        }
        $this->container['personal_number'] = $personal_number;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

}


