<?php
/**
 * WatchlistMeshPep
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Onfido Public API v3.6
 *
 * The Onfido Public API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Onfido\Model;

use \ArrayAccess;
use \Onfido\ObjectSerializer;

/**
 * WatchlistMeshPep Class Doc Comment
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WatchlistMeshPep implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'watchlist_mesh_pep';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'aml_types' => 'string[]',
        'active_end_dates' => 'string[]',
        'active_start_dates' => 'string[]',
        'country_codes' => 'string[]',
        'fields' => '\Onfido\Model\WatchlistMeshField[]',
        'identifier' => 'string',
        'listing_ended_utc' => 'string',
        'listing_started_utc' => 'string',
        'name' => 'string',
        'political_parties' => 'string[]',
        'political_positions' => 'string[]',
        'political_regions' => 'string[]',
        'related_urls' => 'string[]',
        'url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'aml_types' => null,
        'active_end_dates' => null,
        'active_start_dates' => null,
        'country_codes' => null,
        'fields' => null,
        'identifier' => null,
        'listing_ended_utc' => null,
        'listing_started_utc' => null,
        'name' => null,
        'political_parties' => null,
        'political_positions' => null,
        'political_regions' => null,
        'related_urls' => null,
        'url' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'aml_types' => true,
        'active_end_dates' => true,
        'active_start_dates' => true,
        'country_codes' => true,
        'fields' => true,
        'identifier' => true,
        'listing_ended_utc' => true,
        'listing_started_utc' => true,
        'name' => true,
        'political_parties' => true,
        'political_positions' => true,
        'political_regions' => true,
        'related_urls' => true,
        'url' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'aml_types' => 'aml_types',
        'active_end_dates' => 'active_end_dates',
        'active_start_dates' => 'active_start_dates',
        'country_codes' => 'country_codes',
        'fields' => 'fields',
        'identifier' => 'identifier',
        'listing_ended_utc' => 'listing_ended_utc',
        'listing_started_utc' => 'listing_started_utc',
        'name' => 'name',
        'political_parties' => 'political_parties',
        'political_positions' => 'political_positions',
        'political_regions' => 'political_regions',
        'related_urls' => 'related_urls',
        'url' => 'url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'aml_types' => 'setAmlTypes',
        'active_end_dates' => 'setActiveEndDates',
        'active_start_dates' => 'setActiveStartDates',
        'country_codes' => 'setCountryCodes',
        'fields' => 'setFields',
        'identifier' => 'setIdentifier',
        'listing_ended_utc' => 'setListingEndedUtc',
        'listing_started_utc' => 'setListingStartedUtc',
        'name' => 'setName',
        'political_parties' => 'setPoliticalParties',
        'political_positions' => 'setPoliticalPositions',
        'political_regions' => 'setPoliticalRegions',
        'related_urls' => 'setRelatedUrls',
        'url' => 'setUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'aml_types' => 'getAmlTypes',
        'active_end_dates' => 'getActiveEndDates',
        'active_start_dates' => 'getActiveStartDates',
        'country_codes' => 'getCountryCodes',
        'fields' => 'getFields',
        'identifier' => 'getIdentifier',
        'listing_ended_utc' => 'getListingEndedUtc',
        'listing_started_utc' => 'getListingStartedUtc',
        'name' => 'getName',
        'political_parties' => 'getPoliticalParties',
        'political_positions' => 'getPoliticalPositions',
        'political_regions' => 'getPoliticalRegions',
        'related_urls' => 'getRelatedUrls',
        'url' => 'getUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('aml_types', $data ?? [], null);
        $this->setIfExists('active_end_dates', $data ?? [], null);
        $this->setIfExists('active_start_dates', $data ?? [], null);
        $this->setIfExists('country_codes', $data ?? [], null);
        $this->setIfExists('fields', $data ?? [], null);
        $this->setIfExists('identifier', $data ?? [], null);
        $this->setIfExists('listing_ended_utc', $data ?? [], null);
        $this->setIfExists('listing_started_utc', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('political_parties', $data ?? [], null);
        $this->setIfExists('political_positions', $data ?? [], null);
        $this->setIfExists('political_regions', $data ?? [], null);
        $this->setIfExists('related_urls', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets aml_types
     *
     * @return string[]|null
     */
    public function getAmlTypes()
    {
        return $this->container['aml_types'];
    }

    /**
     * Sets aml_types
     *
     * @param string[]|null $aml_types aml_types
     *
     * @return self
     */
    public function setAmlTypes($aml_types)
    {
        if (is_null($aml_types)) {
            array_push($this->openAPINullablesSetToNull, 'aml_types');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('aml_types', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['aml_types'] = $aml_types;

        return $this;
    }

    /**
     * Gets active_end_dates
     *
     * @return string[]|null
     */
    public function getActiveEndDates()
    {
        return $this->container['active_end_dates'];
    }

    /**
     * Sets active_end_dates
     *
     * @param string[]|null $active_end_dates active_end_dates
     *
     * @return self
     */
    public function setActiveEndDates($active_end_dates)
    {
        if (is_null($active_end_dates)) {
            array_push($this->openAPINullablesSetToNull, 'active_end_dates');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('active_end_dates', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['active_end_dates'] = $active_end_dates;

        return $this;
    }

    /**
     * Gets active_start_dates
     *
     * @return string[]|null
     */
    public function getActiveStartDates()
    {
        return $this->container['active_start_dates'];
    }

    /**
     * Sets active_start_dates
     *
     * @param string[]|null $active_start_dates active_start_dates
     *
     * @return self
     */
    public function setActiveStartDates($active_start_dates)
    {
        if (is_null($active_start_dates)) {
            array_push($this->openAPINullablesSetToNull, 'active_start_dates');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('active_start_dates', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['active_start_dates'] = $active_start_dates;

        return $this;
    }

    /**
     * Gets country_codes
     *
     * @return string[]|null
     */
    public function getCountryCodes()
    {
        return $this->container['country_codes'];
    }

    /**
     * Sets country_codes
     *
     * @param string[]|null $country_codes country_codes
     *
     * @return self
     */
    public function setCountryCodes($country_codes)
    {
        if (is_null($country_codes)) {
            array_push($this->openAPINullablesSetToNull, 'country_codes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('country_codes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['country_codes'] = $country_codes;

        return $this;
    }

    /**
     * Gets fields
     *
     * @return \Onfido\Model\WatchlistMeshField[]|null
     */
    public function getFields()
    {
        return $this->container['fields'];
    }

    /**
     * Sets fields
     *
     * @param \Onfido\Model\WatchlistMeshField[]|null $fields fields
     *
     * @return self
     */
    public function setFields($fields)
    {
        if (is_null($fields)) {
            array_push($this->openAPINullablesSetToNull, 'fields');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fields', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fields'] = $fields;

        return $this;
    }

    /**
     * Gets identifier
     *
     * @return string|null
     */
    public function getIdentifier()
    {
        return $this->container['identifier'];
    }

    /**
     * Sets identifier
     *
     * @param string|null $identifier identifier
     *
     * @return self
     */
    public function setIdentifier($identifier)
    {
        if (is_null($identifier)) {
            array_push($this->openAPINullablesSetToNull, 'identifier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('identifier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['identifier'] = $identifier;

        return $this;
    }

    /**
     * Gets listing_ended_utc
     *
     * @return string|null
     */
    public function getListingEndedUtc()
    {
        return $this->container['listing_ended_utc'];
    }

    /**
     * Sets listing_ended_utc
     *
     * @param string|null $listing_ended_utc listing_ended_utc
     *
     * @return self
     */
    public function setListingEndedUtc($listing_ended_utc)
    {
        if (is_null($listing_ended_utc)) {
            array_push($this->openAPINullablesSetToNull, 'listing_ended_utc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('listing_ended_utc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['listing_ended_utc'] = $listing_ended_utc;

        return $this;
    }

    /**
     * Gets listing_started_utc
     *
     * @return string|null
     */
    public function getListingStartedUtc()
    {
        return $this->container['listing_started_utc'];
    }

    /**
     * Sets listing_started_utc
     *
     * @param string|null $listing_started_utc listing_started_utc
     *
     * @return self
     */
    public function setListingStartedUtc($listing_started_utc)
    {
        if (is_null($listing_started_utc)) {
            array_push($this->openAPINullablesSetToNull, 'listing_started_utc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('listing_started_utc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['listing_started_utc'] = $listing_started_utc;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets political_parties
     *
     * @return string[]|null
     */
    public function getPoliticalParties()
    {
        return $this->container['political_parties'];
    }

    /**
     * Sets political_parties
     *
     * @param string[]|null $political_parties political_parties
     *
     * @return self
     */
    public function setPoliticalParties($political_parties)
    {
        if (is_null($political_parties)) {
            array_push($this->openAPINullablesSetToNull, 'political_parties');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('political_parties', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['political_parties'] = $political_parties;

        return $this;
    }

    /**
     * Gets political_positions
     *
     * @return string[]|null
     */
    public function getPoliticalPositions()
    {
        return $this->container['political_positions'];
    }

    /**
     * Sets political_positions
     *
     * @param string[]|null $political_positions political_positions
     *
     * @return self
     */
    public function setPoliticalPositions($political_positions)
    {
        if (is_null($political_positions)) {
            array_push($this->openAPINullablesSetToNull, 'political_positions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('political_positions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['political_positions'] = $political_positions;

        return $this;
    }

    /**
     * Gets political_regions
     *
     * @return string[]|null
     */
    public function getPoliticalRegions()
    {
        return $this->container['political_regions'];
    }

    /**
     * Sets political_regions
     *
     * @param string[]|null $political_regions political_regions
     *
     * @return self
     */
    public function setPoliticalRegions($political_regions)
    {
        if (is_null($political_regions)) {
            array_push($this->openAPINullablesSetToNull, 'political_regions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('political_regions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['political_regions'] = $political_regions;

        return $this;
    }

    /**
     * Gets related_urls
     *
     * @return string[]|null
     */
    public function getRelatedUrls()
    {
        return $this->container['related_urls'];
    }

    /**
     * Sets related_urls
     *
     * @param string[]|null $related_urls related_urls
     *
     * @return self
     */
    public function setRelatedUrls($related_urls)
    {
        if (is_null($related_urls)) {
            array_push($this->openAPINullablesSetToNull, 'related_urls');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('related_urls', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['related_urls'] = $related_urls;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            array_push($this->openAPINullablesSetToNull, 'url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['url'] = $url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


