<?php
/**
 * WatchlistEnhancedBreakdown
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Onfido Public API v3.6
 *
 * The Onfido Public API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Onfido\Model;

use \ArrayAccess;
use \Onfido\ObjectSerializer;

/**
 * WatchlistEnhancedBreakdown Class Doc Comment
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WatchlistEnhancedBreakdown implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'watchlist_enhanced_breakdown';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'politically_exposed_person' => '\Onfido\Model\WatchlistAmlBreakdownPoliticallyExposedPerson',
        'sanction' => '\Onfido\Model\WatchlistAmlBreakdownSanction',
        'adverse_media' => '\Onfido\Model\WatchlistAmlBreakdownAdverseMedia',
        'monitored_lists' => '\Onfido\Model\WatchlistAmlBreakdownLegalAndRegulatoryWarnings'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'politically_exposed_person' => null,
        'sanction' => null,
        'adverse_media' => null,
        'monitored_lists' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'politically_exposed_person' => false,
        'sanction' => false,
        'adverse_media' => false,
        'monitored_lists' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'politically_exposed_person' => 'politically_exposed_person',
        'sanction' => 'sanction',
        'adverse_media' => 'adverse_media',
        'monitored_lists' => 'monitored_lists'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'politically_exposed_person' => 'setPoliticallyExposedPerson',
        'sanction' => 'setSanction',
        'adverse_media' => 'setAdverseMedia',
        'monitored_lists' => 'setMonitoredLists'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'politically_exposed_person' => 'getPoliticallyExposedPerson',
        'sanction' => 'getSanction',
        'adverse_media' => 'getAdverseMedia',
        'monitored_lists' => 'getMonitoredLists'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('politically_exposed_person', $data ?? [], null);
        $this->setIfExists('sanction', $data ?? [], null);
        $this->setIfExists('adverse_media', $data ?? [], null);
        $this->setIfExists('monitored_lists', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets politically_exposed_person
     *
     * @return \Onfido\Model\WatchlistAmlBreakdownPoliticallyExposedPerson|null
     */
    public function getPoliticallyExposedPerson()
    {
        return $this->container['politically_exposed_person'];
    }

    /**
     * Sets politically_exposed_person
     *
     * @param \Onfido\Model\WatchlistAmlBreakdownPoliticallyExposedPerson|null $politically_exposed_person politically_exposed_person
     *
     * @return self
     */
    public function setPoliticallyExposedPerson($politically_exposed_person)
    {
        if (is_null($politically_exposed_person)) {
            throw new \InvalidArgumentException('non-nullable politically_exposed_person cannot be null');
        }
        $this->container['politically_exposed_person'] = $politically_exposed_person;

        return $this;
    }

    /**
     * Gets sanction
     *
     * @return \Onfido\Model\WatchlistAmlBreakdownSanction|null
     */
    public function getSanction()
    {
        return $this->container['sanction'];
    }

    /**
     * Sets sanction
     *
     * @param \Onfido\Model\WatchlistAmlBreakdownSanction|null $sanction sanction
     *
     * @return self
     */
    public function setSanction($sanction)
    {
        if (is_null($sanction)) {
            throw new \InvalidArgumentException('non-nullable sanction cannot be null');
        }
        $this->container['sanction'] = $sanction;

        return $this;
    }

    /**
     * Gets adverse_media
     *
     * @return \Onfido\Model\WatchlistAmlBreakdownAdverseMedia|null
     */
    public function getAdverseMedia()
    {
        return $this->container['adverse_media'];
    }

    /**
     * Sets adverse_media
     *
     * @param \Onfido\Model\WatchlistAmlBreakdownAdverseMedia|null $adverse_media adverse_media
     *
     * @return self
     */
    public function setAdverseMedia($adverse_media)
    {
        if (is_null($adverse_media)) {
            throw new \InvalidArgumentException('non-nullable adverse_media cannot be null');
        }
        $this->container['adverse_media'] = $adverse_media;

        return $this;
    }

    /**
     * Gets monitored_lists
     *
     * @return \Onfido\Model\WatchlistAmlBreakdownLegalAndRegulatoryWarnings|null
     */
    public function getMonitoredLists()
    {
        return $this->container['monitored_lists'];
    }

    /**
     * Sets monitored_lists
     *
     * @param \Onfido\Model\WatchlistAmlBreakdownLegalAndRegulatoryWarnings|null $monitored_lists monitored_lists
     *
     * @return self
     */
    public function setMonitoredLists($monitored_lists)
    {
        if (is_null($monitored_lists)) {
            throw new \InvalidArgumentException('non-nullable monitored_lists cannot be null');
        }
        $this->container['monitored_lists'] = $monitored_lists;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


