<?php
/**
 * WorkflowRunStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Onfido API v3.6
 *
 * The Onfido API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Onfido\Model;
use \Onfido\ObjectSerializer;

/**
 * WorkflowRunStatus Class Doc Comment
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WorkflowRunStatus
{
    /**
     * Possible values of this enum
     */
    public const PROCESSING = 'processing';

    public const AWAITING_INPUT = 'awaiting_input';

    public const AWAITING_CLIENT_INPUT = 'awaiting_client_input';

    public const APPROVED = 'approved';

    public const DECLINED = 'declined';

    public const REVIEW = 'review';

    public const ABANDONED = 'abandoned';

    public const ERROR = 'error';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PROCESSING,
            self::AWAITING_INPUT,
            self::AWAITING_CLIENT_INPUT,
            self::APPROVED,
            self::DECLINED,
            self::REVIEW,
            self::ABANDONED,
            self::ERROR,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}


