<?php
/**
 * CheckTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Onfido;

use PHPUnit\Framework\TestCase;

/**
 * CheckTest Class Doc Comment
 *
 * @category    Class
 * @description Check
 * @package     Onfido
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CheckTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Check"
     */
    public function testCheck()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "href"
     */
    public function testPropertyHref()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "result"
     */
    public function testPropertyResult()
    {
    }

    /**
     * Test attribute "download_uri"
     */
    public function testPropertyDownloadUri()
    {
    }

    /**
     * Test attribute "form_uri"
     */
    public function testPropertyFormUri()
    {
    }

    /**
     * Test attribute "redirect_uri"
     */
    public function testPropertyRedirectUri()
    {
    }

    /**
     * Test attribute "results_uri"
     */
    public function testPropertyResultsUri()
    {
    }

    /**
     * Test attribute "report_names"
     */
    public function testPropertyReportNames()
    {
    }

    /**
     * Test attribute "applicant_id"
     */
    public function testPropertyApplicantId()
    {
    }

    /**
     * Test attribute "privacy_notices_read_consent_given"
     */
    public function testPropertyPrivacyNoticesReadConsentGiven()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "applicant_provides_data"
     */
    public function testPropertyApplicantProvidesData()
    {
    }

    /**
     * Test attribute "suppress_form_emails"
     */
    public function testPropertySuppressFormEmails()
    {
    }

    /**
     * Test attribute "asynchronous"
     */
    public function testPropertyAsynchronous()
    {
    }

    /**
     * Test attribute "report_ids"
     */
    public function testPropertyReportIds()
    {
    }

    /**
     * Test attribute "document_ids"
     */
    public function testPropertyDocumentIds()
    {
    }

    /**
     * Test attribute "consider"
     */
    public function testPropertyConsider()
    {
    }

    /**
     * Test attribute "sub_result"
     */
    public function testPropertySubResult()
    {
    }
}
