<?php
/**
 * ReportTypeGroupTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Onfido;

use PHPUnit\Framework\TestCase;

/**
 * ReportTypeGroupTest Class Doc Comment
 *
 * @category    Class
 * @description ReportTypeGroup
 * @package     Onfido
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ReportTypeGroupTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReportTypeGroup"
     */
    public function testReportTypeGroup()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "group_only"
     */
    public function testPropertyGroupOnly()
    {
    }

    /**
     * Test attribute "report_types"
     */
    public function testPropertyReportTypes()
    {
    }
}
