<?php
/**
 * DefaultApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Onfido\Test\Api;

use \Onfido\Configuration;
use \Onfido\ApiException;
use \Onfido\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Onfido
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelReport
     *
     * This endpoint is for cancelling individual paused reports..
     *
     */
    public function testCancelReport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createApplicant
     *
     * Create Applicant.
     *
     */
    public function testCreateApplicant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCheck
     *
     * Create a check.
     *
     */
    public function testCreateCheck()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createWebhook
     *
     * Create a webhook.
     *
     */
    public function testCreateWebhook()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWebhook
     *
     * Delete a webhook.
     *
     */
    public function testDeleteWebhook()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for destroyApplicant
     *
     * Delete Applicant.
     *
     */
    public function testDestroyApplicant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadCheck
     *
     * Download a check raw data.
     *
     */
    public function testDownloadCheck()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadDocument
     *
     * Download a documents raw data.
     *
     */
    public function testDownloadDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadLivePhoto
     *
     * Download live photo.
     *
     */
    public function testDownloadLivePhoto()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadLiveVideo
     *
     * Download live video.
     *
     */
    public function testDownloadLiveVideo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadMotionCapture
     *
     * Download motion capture.
     *
     */
    public function testDownloadMotionCapture()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editWebhook
     *
     * Edit a webhook.
     *
     */
    public function testEditWebhook()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findAddresses
     *
     * Search for addresses by postcode.
     *
     */
    public function testFindAddresses()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findApplicant
     *
     * Retrieve Applicant.
     *
     */
    public function testFindApplicant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findCheck
     *
     * Retrieve a Check.
     *
     */
    public function testFindCheck()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findDocument
     *
     * A single document can be retrieved by calling this endpoint with the document’s unique identifier..
     *
     */
    public function testFindDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findLivePhoto
     *
     * Retrieve live photo.
     *
     */
    public function testFindLivePhoto()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findLiveVideo
     *
     * Retrieve live video.
     *
     */
    public function testFindLiveVideo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findMotionCapture
     *
     * Retrieve motion capture.
     *
     */
    public function testFindMotionCapture()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findReport
     *
     * A single report can be retrieved using this endpoint with the corresponding unique identifier..
     *
     */
    public function testFindReport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findWebhook
     *
     * Retrieve a Webhook.
     *
     */
    public function testFindWebhook()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for frameLiveVideo
     *
     * Download live video frame.
     *
     */
    public function testFrameLiveVideo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for frameMotionCapture
     *
     * Download motion capture frame.
     *
     */
    public function testFrameMotionCapture()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateSdkToken
     *
     * Generate a SDK token.
     *
     */
    public function testGenerateSdkToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listApplicants
     *
     * List Applicants.
     *
     */
    public function testListApplicants()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listChecks
     *
     * Retrieve Checks.
     *
     */
    public function testListChecks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listDocuments
     *
     * List documents.
     *
     */
    public function testListDocuments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listLivePhotos
     *
     * List live photos.
     *
     */
    public function testListLivePhotos()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listLiveVideos
     *
     * List live videos.
     *
     */
    public function testListLiveVideos()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMotionCaptures
     *
     * List motion captures.
     *
     */
    public function testListMotionCaptures()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listReports
     *
     * All the reports belonging to a particular check can be listed from this endpoint..
     *
     */
    public function testListReports()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listWebhooks
     *
     * List webhooks.
     *
     */
    public function testListWebhooks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restoreApplicant
     *
     * Restore Applicant.
     *
     */
    public function testRestoreApplicant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resumeCheck
     *
     * Resume a Check.
     *
     */
    public function testResumeCheck()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resumeReport
     *
     * This endpoint is for resuming individual paused reports..
     *
     */
    public function testResumeReport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateApplicant
     *
     * Update Applicant.
     *
     */
    public function testUpdateApplicant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadDocument
     *
     * Upload a document.
     *
     */
    public function testUploadDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadLivePhoto
     *
     * Upload live photo.
     *
     */
    public function testUploadLivePhoto()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
