# This workflow will install PHP dependencies, run tests and lint with a variety of PHP versions
# For more information see: https://github.com/marketplace/actions/composer-php-actions

name: PHP package

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'release/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.3']

    steps:
    - uses: actions/checkout@v3
    - name: Set up PHP ${{ matrix.php-version }}
      uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php-version }}
    - name: Test with phpunit
      if: ${{ matrix.php-version == '8.3' &&
              github.event.pull_request.head.repo.full_name == github.repository &&
              github.actor != 'dependabot[bot]' }}
      run: |
        vendor/bin/phpunit
      env:
          ONFIDO_API_TOKEN: ${{secrets.ONFIDO_API_TOKEN}}
          ONFIDO_SAMPLE_APPLICANT_ID: ${{secrets.ONFIDO_SAMPLE_APPLICANT_ID}}
          ONFIDO_SAMPLE_VIDEO_ID_1: ${{secrets.ONFIDO_SAMPLE_VIDEO_ID_1}}
          ONFIDO_SAMPLE_VIDEO_ID_2: ${{secrets.ONFIDO_SAMPLE_VIDEO_ID_2}}
          ONFIDO_SAMPLE_MOTION_ID_1: ${{secrets.ONFIDO_SAMPLE_MOTION_ID_1}}
          ONFIDO_SAMPLE_MOTION_ID_2: ${{secrets.ONFIDO_SAMPLE_MOTION_ID_2}}
